### ISSUE TITLE
(#212) Portal theming (excluding events)

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/alnap#132]
First of all get theme working on one portal (Portal 1) before attempting to apply them to other portals.

### Done criteria
- [x] Set up base'domain theme based on the alnap theme (sub sub theme) 
- [x] change header footer and other elements to match design
- [x] Theme other pages as required but in general most pages follow main alnap theme
- [x] change nav colour, hovers etc as per Cat's design
- [x] portals logo, name of portal will go to the right of this (see designs below)
- [x] add points estimate to #238
- [x] BLOCKER - Progress further with base theme (e.g. events)
- [x] ISSUE - Button icons in header need to be centred
- [x] ISSUE - on search the grid / list view icons move up in the filter box
- [x] ISSUE - the filters don't automatically filter on selection
- [x] ISSUE - On search the 'from the start of and to the end of' filters move position which is odd
- [x] ISSUE - on test resources page the sahre icons are too low
- [x] ISSUE - Missing 'Hosted by ALNAP' bar
- [x] ISSUE - Text in buttons in header should be 16px (currently 14px)
- [x] ISSUE - Main nav text should be Oswald Medium (currently regular)
- [x] ISSUE - Clicking search icon displays search box in wrong place
- [x] ISSUE - Active crumb colour #70706E
- [x] ISSUE - Crumb text should be bold
- [x] ISSUE - Hero text - Intro should be Roboto Regular 24px, body should be Roboto Regular 18px
- [x] ISSUE - More space below titles
- [x] ISSUE - Resource date 16px
- [x] ISSUE - 'Member only' tag text should be #6C7881 and box outline should be #C4C9CD
- [x] ISSUE - Social media buttons in footer should be 48x48 px
- [x] ISSUE - About - add 10px more space around intro text/expandable box
- [x] ISSUE - Resources - Advanced search plus button should be portal colour (#862046 in the urban portal)
- [x] ISSUE - Blogs - grey buttons on RHS to move up, in line with the top of the search blogs box (When logged out the boxes line up like in the design)
- [x] ISSUE - Second title uses colour icons, should be grey like main title (http://alnap-domain1.mrmdev.co.uk/test-resource)
- [x] ISSUE - Links in the Twitter feed should be #0E6794

**Colours**
Each portal needs it's own colour - we only need enough colours for the portals they have right now. 
- [ ] Work out where the colour is applied
- [ ] Work out what the colours are (take a colour from their logo?)
- [ ] Apply the colours!

---
### Designs
- [Portal example - Principled...](https://invis.io/5SCAXSEBM)
- [Portal example - Urban](https://invis.io/CQCCBR53T)
- [Portal style guide](https://invis.io/92CRDWLXS)

**Comment by angievanhegan** [comment]
Notes from Slack: 
- Designs were updated on 25 July
-  get involved boxes up were moved up
- search library was moved up into that section as a 4th button
