### ISSUE TITLE
Sprint goal: Bits and bobs

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/alnap#137]
- [ ] Browser/device testing #254
- [ ] Review/adjust content type aliases & breadcrumbs #221
- [ ] Contact us #252
- [ ] Manual redirects setup #255

**Comment by angievanhegan** [comment]
@russ-manta we have this in the backlog, but I'm assuming we're mostly testing as we go? Thanks
