### ISSUE TITLE
Sprint goal: Events

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#210]
- [ ] Build & theme event content type #30
- [ ] Build & theme events search #75
- [ ] Build & theme PAST events view with search #163
- [ ] Build Annual meetings landing page #35

---
### Designs
- [Events wide](https://invis.io/VPC8MGQ6E)
- [Events wide search](https://invis.io/U6C8MHW2E)
- [Events node wide](https://invis.io/J4C0FZGGS)
- [Event coverage](https://invis.io/MTC3CTGWC)
- [Annual meetings landing](https://invis.io/T2C3JAS79)
