### ISSUE TITLE
Sprint goal: Workflow and content management

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#213]
- [ ]  Bulk editing of tags #94
- [ ] Build resource management view #71
- [ ] Setup the taxonomy for tagging resources / events / news #15
