### ISSUE TITLE
Sprint goal: Search & search based recommendations

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#214]
- [ ] Research search based recommendation  #246
- [ ] Search based recommendations #92
- [ ] Build and theme - showing recommendations based on preferences on user account page #175
- [ ] Build and theme site search #127
- [x] Build related content views #70
