### ISSUE TITLE
Sprint goal: Resources (part 2)

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#216]
- [ ] Capture email address for person downloading specific resources #174
- [ ] Member only resources #64
- [ ] Add note to explain what the portals are on the HELP page #167
- [ ] Redesign portals section on resources search #161
- [ ] Book marking resources #91
- [ ] Remove end date from resources #225
- [ ] Migrate resources #129
- [ ] Ensure organisation is always referred to as 'organisation' and not agency #226
- [ ] Question: What is resource category on the individual resource? #228
