### ISSUE TITLE
Sprint goal: Go live tasks

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#247]
- [ ] Migrate blog comments programatically #206
- [ ] Final resource migration #129
- [ ] Final user migration #248
- [ ] Setup https #86
- [ ] Move to live #134
- [ ] Run link checker over the site #236
- [ ] Send out password reset email #257
- [ ] Set Google Analytics #133
- [ ] Redirects for resources #131
